[project]
name = "lingusync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "huggingface-hub>=2.0.0",
    "pandas>=3.0.5",
    "platformdirs>=4.11.8",
    "safetensors>=0.8.0",
    "sqlalchemy>=2.0.52",
    "torch>=2.14.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu132"
